language: python
python:
  - "2.7"
  - "2.6"
before_install:
  - wget http://www.riverbankcomputing.com/static/Downloads/sip4/sip-4.13.3.tar.gz
  - tar zxvf sip-4.13.3.tar.gz
  - cd sip-4.13.3/
  - python configure.py
  - make
  - sudo make install
  - cd ..
  - python -c 'import sip'
  - sudo apt-get install libqt4-dev python-qt4 pyqt4-dev-tools qt4-designer
  # - wget http://www.riverbankcomputing.com/static/Downloads/PyQt4/PyQt-x11-gpl-4.9.4.tar.gz
  # - tar zxvf PyQt-x11-gpl-4.9.4.tar.gz
  # - cd PyQt-x11-gpl-4.9.4/
  # - echo 'yes' | python configure.py
  # - make
  # - sudo make install
  # - cd ..
  - python -c 'import PyQt4'
  - python -c 'import PyQt4.QtCore'
install:
  - pip install nose
# command to run tests, e.g. python setup.py test
script:
  - nosetests
